name: botway_dart
description: |
  Dart client package for Botway.
  After creating a new dart botway project, you need to use your tokens to connect with your bot.
version: 0.1.1
homepage: https://github.com/abdfnx/botway

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  path: ^1.8.2
  yaml: ^3.1.1
