name: Deploy To Botway CDN

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy-botway-cdn:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - name: Get Static Files
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: cd assets && deno task add-data

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "cdn-botway"
          entrypoint: ./main.ts
          root: ./assets
