name: Release

on:
  push:
    tags:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  GITHUB_ACTIONS_NAME: "github-actions[bot]"
  GITHUB_ACTIONS_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"

permissions: write-all

jobs:
  build-botway:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21"

      - name: Set up Task
        uses: arduino/setup-task@v1

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true

      - name: Set up Tag
        id: ghtag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build
        run: |
          task release
          task upload-scoop-manifest
          npx prettier botway.json -w
          git config --local user.email "${{ env.GITHUB_ACTIONS_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_ACTIONS_NAME }}"
          git diff --cached
          git add .
          git commit -m "Scoop update for botway version ${TAG}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
